"""
Shared state definitions for the LangGraph multi-agent workflow.

Defines the fields and reducers that flow through the sequential analysis
and recommendation graph.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, Optional, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class InvestmentAgentState(TypedDict):
    """Shared state flowing through the LangGraph investment analysis pipeline.

    Aggregates messages, execution parameters, calculated metrics, and intermediate
    outputs generated by the specialized agents.
    """

    # Messages track conversation history/interaction with the user or between agents
    messages: Annotated[list[BaseMessage], add_messages]

    # Target list of assets to analyze (e.g. ['AAPL', 'RELIANCE.NS'])
    tickers: list[str]

    # Raw market prices, fundamentals and news fetched by researcher
    # Schema: {ticker: MarketDataBundle.model_dump()}
    market_data: Optional[dict[str, Any]]

    # Signals from technical analysis
    # Schema: {ticker: {indicator: value/signal}}
    technical_analysis: Optional[dict[str, Any]]

    # Risk metrics calculated for each asset
    # Schema: {ticker: {metric: value}}
    risk_analysis: Optional[dict[str, Any]]

    # Sentiment analysis results from news
    # Schema: {ticker: {weighted_sentiment: float, classification: str}}
    sentiment_analysis: Optional[dict[str, Any]]

    # Normalized composite scores (0-100) and recommendation signals
    # Schema: {ticker: {risk_score: float, signal: str, confidence: float}}
    composite_scores: Optional[dict[str, Any]]

    # Output portfolio optimization allocations and metrics
    # Schema: {weights: {ticker: float}, expected_return: float, sharpe_ratio: float}
    portfolio_recommendation: Optional[dict[str, Any]]

    # User gate decision: 'approve', 'reject', or 'modify'
    human_approval: Optional[str]

    # Path to generated daily report (PDF / HTML)
    final_report: Optional[str]

    # Append-only execution audit log tracking step progression
    audit_log: Annotated[list[str], operator.add]

    # Append-only error tracking log
    error_log: Annotated[list[str], operator.add]

    # Next node to execute
    next: str
